# styles.py

# Monochrome, Material-inspired tokens (light,dark)
PRIMARY = ("#4A4A4A", "#303030")
ON_PRIMARY = ("#FFFFFF", "#FFFFFF")
PRIMARY_CONTAINER = ("#EAEAEA", "#3A3A3A")
ON_PRIMARY_CONTAINER = ("#1F1F1F", "#EAEAEA")

SECONDARY = ("#5E5E5E", "#3C3C3C")
ON_SECONDARY = ("#FFFFFF", "#FFFFFF")
SECONDARY_CONTAINER = ("#E0E0E0", "#303030")
ON_SECONDARY_CONTAINER = ("#1F1F1F", "#EAEAEA")

SURFACE = ("#F5F5F5", "#2C2C2C")
ON_SURFACE = ("#1C1C1C", "#EAEAEA")
SURFACE_VARIANT = ("#E0E0E0", "#3A3A3A")
ON_SURFACE_VARIANT = ("#707070", "#B5B5B5")

ERROR = ("#C44141", "#C44141")
ON_ERROR = ("#FFFFFF", "#FFFFFF")
ERROR_CONTAINER = ("#F0D6D6", "#5A2A2A")
ON_ERROR_CONTAINER = ("#5A2A2A", "#F0D6D6")

# Buttons (monochrome by default)
DEFAULT_BUTTON_FG_COLOR = ("#4A4A4A", "#3F3F3F")
DEFAULT_BUTTON_TEXT_COLOR = ON_PRIMARY
CANCEL_BUTTON_COLOR = ("#B0B0B0", "#4D4D4D")
CANCEL_BUTTON_TEXT_COLOR = ("#000000", "#FFFFFF")
DELETE_BUTTON_COLOR = ERROR[0]
DELETE_BUTTON_HOVER_COLOR = "#A43737"
FILE_ATTACH_BUTTON_COLOR = SECONDARY
MATRIX_BUTTON_COLOR = SECONDARY

# Borders / focus (neutral)
HIGHLIGHT_BORDER_COLOR = ("#888888", "#9A9A9A")

# Notifications (subtle tones allowed)
NOTIFICATION_COLORS = {
    "info":    ("#E6E6E6", "#3A3A3A"),
    "warning": ("#F2F2E6", "#4A4A3A"),
    "error":   ERROR_CONTAINER,
    "success": ("#E6F2EA", "#2F3A33"),
}

# Surfaces / text
HISTORY_ITEM_FG_COLOR = SURFACE
HISTORY_ITEM_TEXT_COLOR = ON_SURFACE
FLOW_RESULT_TEXT_COLOR = ("#2E7D32", "#9CCC65")

# Matrix top bars
MATRIX_TOP_BG_COLOR = ("#F5F5F5", "#252525")

# --- フォント定義 (変更なし) ---
FONT_BOLD = ("bold", 14)
FONT_NORMAL = (None, 12)
FONT_LARGE_BOLD = (None, 24, "bold")

# --- サイズ・ジオメトリ定義 (変更なし) ---
ACTION_SELECTOR_BUTTON_HEIGHT = 30
ACTION_SELECTOR_SPACING = 5
ACTION_SELECTOR_MARGIN = 10
ACTION_SELECTOR_GEOMETRY = "350x500"
HIGHLIGHT_BORDER_WIDTH = 1

NOTIFICATION_POPUP_INITIAL_WIDTH = 500
NOTIFICATION_POPUP_ALPHA = 0.9

PROMPT_EDITOR_GEOMETRY = "500x800"
PROMPT_SELECTION_GEOMETRY = "400x800"
SETTINGS_WINDOW_GEOMETRY = "520x380"
MAIN_WINDOW_GEOMETRY = "480x600"

HISTORY_FRAME_HEIGHT = 200

# --- Matrix Batch Processor ---
# マトリックス関連の色もモノクロームに統一
MATRIX_WINDOW_GEOMETRY = "1400x700"
MATRIX_HEADER_BORDER_COLOR = ("#707070", "#3F3F3F")
MATRIX_CELL_BORDER_COLOR = MATRIX_HEADER_BORDER_COLOR
MATRIX_DELETE_BUTTON_COLOR = ERROR[0]
# MATRIX_DELETE_BUTTON_COLOR = "#C44141"  # 彩度を抑えた赤
MATRIX_DELETE_BUTTON_HOVER_COLOR = "#A43737" # 少し濃い赤
MATRIX_FONT_BOLD = (None, 12, "bold")
MATRIX_RESULT_FONT = (None, 10)
MATRIX_IMAGE_THUMBNAIL_SIZE = (50, 50)
MATRIX_POPUP_GEOMETRY = "400x400"
MATRIX_RESULT_CELL_HEIGHT = 60
MATRIX_CELL_WIDTH = 250 # セルの固定幅を追加
# 固定（左端）列の推奨最小幅（行番号・削除ボタン・入力・添付/履歴ボタンが収まる程度）
MATRIX_FIXED_COL_WIDTH = 240
MATRIX_SUMMARY_FG_COLOR = PRIMARY_CONTAINER

HISTORY_SELECTOR_POPUP_WIDTH = 350
HISTORY_SELECTOR_POPUP_MAX_HEIGHT = 400

# メインキャンバスの背景色
MATRIX_CANVAS_BACKGROUND_COLOR = SURFACE

# --- Drag & drop highlight colors ---
# 行ドラッグ時に現在掴んでいる行を示す背景色。
# 左がライトモード用、右がダークモード用の色です。
DRAG_ACTIVE_ROW_COLOR = ("#EAEAEA", "#3A3A3A")
# ドロップターゲットを示す背景色。アクティブ行とは異なる色で区別します。
DRAG_TARGET_ROW_COLOR = ("#DDDDDD", "#333333")

# --- Popup スタイル ---
# ポップアップウィンドウの背景色とテキスト色を統一します。
POPUP_BG_COLOR = SURFACE
POPUP_TEXT_COLOR = ON_SURFACE

# --- 添付ファイル表示エリア ---
# 左側の添付ファイル名表示パネルの枠と背景
ATTACH_AREA_BORDER_COLOR = SURFACE_VARIANT
ATTACH_AREA_BG_COLOR = ("#F0F0F0", "#2A2A2A")
