# styles.py

# =================================================================================================
# MODERN UI THEME DEFINITIONS
# =================================================================================================
#
# This style guide provides a unified and modern look for the application.
# It defines a clear color hierarchy for both light and dark modes.
#
# - APP_BG_COLOR: The main background color of the window.
# - FRAME_BG_COLOR: The background color for frames and containers.
# - COMPONENT_BG_COLOR: The background for input fields, list items, etc.
# - ACCENT_COLOR: The primary color for buttons, links, and highlights.
# - TEXT_COLOR: The primary text color.
# - TEXT_SECONDARY_COLOR: The color for less important text.
# - DESTRUCTIVE_COLOR: The color for actions that delete data.
#
# =================================================================================================

# --- 1. Core Color Palette ---

# Light Mode Colors
LIGHT_APP_BG = "#F0F2F5"
LIGHT_FRAME_BG = "#FFFFFF"
LIGHT_COMPONENT_BG = "#F0F2F5" # Same as App BG for a flatter look
LIGHT_TEXT = "#050505"
LIGHT_TEXT_SECONDARY = "#65676B"
LIGHT_ACCENT = "#1877F2"
LIGHT_ACCENT_HOVER = "#166FE5"
LIGHT_CANCEL_BG = "#E4E6EB"
LIGHT_CANCEL_HOVER = "#D8DADE"
LIGHT_DESTRUCTIVE = "#FA383E"
LIGHT_DESTRUCTIVE_HOVER = "#E0282E"
LIGHT_BORDER = "#CED0D4"
LIGHT_DRAG_BG = "#DDE6F7"

# Dark Mode Colors
DARK_APP_BG = "#18191A"
DARK_FRAME_BG = "#242526"
DARK_COMPONENT_BG = "#3A3B3C"
DARK_TEXT = "#E4E6EB"
DARK_TEXT_SECONDARY = "#B0B3B8"
DARK_ACCENT = "#2D88FF"
DARK_ACCENT_HOVER = "#1B74E4"
DARK_CANCEL_BG = "#4E4F50"
DARK_CANCEL_HOVER = "#5A5B5C"
DARK_DESTRUCTIVE = "#F04C50"
DARK_DESTRUCTIVE_HOVER = "#D83C40"
DARK_BORDER = "#47494A"
DARK_DRAG_BG = "#3A4A6F"

# --- 2. Theme Assignments (Tuples: Light, Dark) ---

# Background Colors
APP_BG_COLOR = (LIGHT_APP_BG, DARK_APP_BG)
FRAME_BG_COLOR = (LIGHT_FRAME_BG, DARK_FRAME_BG)
POPUP_BG_COLOR = (LIGHT_FRAME_BG, DARK_FRAME_BG)
COMPONENT_BG_COLOR = (LIGHT_COMPONENT_BG, DARK_COMPONENT_BG)

# Text Colors
TEXT_COLOR = (LIGHT_TEXT, DARK_TEXT)
TEXT_SECONDARY_COLOR = (LIGHT_TEXT_SECONDARY, DARK_TEXT_SECONDARY)
POPUP_TEXT_COLOR = TEXT_COLOR

# Button Colors
DEFAULT_BUTTON_FG_COLOR = (LIGHT_ACCENT, DARK_ACCENT)
DEFAULT_BUTTON_HOVER_COLOR = (LIGHT_ACCENT_HOVER, DARK_ACCENT_HOVER)
DEFAULT_BUTTON_TEXT_COLOR = ("#FFFFFF", DARK_TEXT)

CANCEL_BUTTON_COLOR = (LIGHT_CANCEL_BG, DARK_CANCEL_BG)
CANCEL_BUTTON_HOVER_COLOR = (LIGHT_CANCEL_HOVER, DARK_CANCEL_HOVER)
CANCEL_BUTTON_TEXT_COLOR = (LIGHT_TEXT, DARK_TEXT)

DELETE_BUTTON_COLOR = (LIGHT_DESTRUCTIVE, DARK_DESTRUCTIVE)
DELETE_BUTTON_HOVER_COLOR = (LIGHT_DESTRUCTIVE_HOVER, DARK_DESTRUCTIVE_HOVER)
DELETE_BUTTON_TEXT_COLOR = ("#FFFFFF", DARK_TEXT)

# Highlight and Border Colors
HIGHLIGHT_BORDER_COLOR = (LIGHT_ACCENT, DARK_ACCENT)
BORDER_COLOR = (LIGHT_BORDER, DARK_BORDER)

# Drag & Drop Colors
DRAG_ACTIVE_ROW_COLOR = (LIGHT_DRAG_BG, DARK_DRAG_BG)
DRAG_TARGET_ROW_COLOR = (LIGHT_DRAG_BG, DARK_DRAG_BG) # Using one color for simplicity

# Notification Popup Colors
NOTIFICATION_COLORS = {
    "info": ("#E7F3FF", "#2E3F56"),      # Light Blue / Dark Blue
    "warning": ("#FFF4E5", "#594225"),   # Light Orange / Dark Orange
    "error": ("#FFE5E6", "#592E2E"),      # Light Red / Dark Red
    "success": ("#E6F7EC", "#2E4F3D")    # Light Green / Dark Green
}

# --- Legacy & Component-Specific Assignments ---
# These variables are kept for compatibility with existing code.
# They are mapped to the new, unified color palette.

# History Items
HISTORY_ITEM_FG_COLOR = (LIGHT_COMPONENT_BG, DARK_COMPONENT_BG)
HISTORY_ITEM_TEXT_COLOR = TEXT_COLOR
FLOW_RESULT_TEXT_COLOR = (LIGHT_DESTRUCTIVE, DARK_DESTRUCTIVE)

# Matrix View
MATRIX_TOP_BG_COLOR = (LIGHT_FRAME_BG, DARK_FRAME_BG)
MATRIX_CANVAS_BACKGROUND_COLOR = (LIGHT_APP_BG, DARK_APP_BG)
MATRIX_HEADER_BORDER_COLOR = BORDER_COLOR
MATRIX_CELL_BORDER_COLOR = BORDER_COLOR
MATRIX_SUMMARY_FG_COLOR = (LIGHT_COMPONENT_BG, DARK_COMPONENT_BG)
MATRIX_DELETE_BUTTON_COLOR = DELETE_BUTTON_COLOR
MATRIX_DELETE_BUTTON_HOVER_COLOR = DELETE_BUTTON_HOVER_COLOR

# Attachment Area (Style updated to be less intrusive)
ATTACH_AREA_BORDER_COLOR = BORDER_COLOR
ATTACH_AREA_BG_COLOR = COMPONENT_BG_COLOR


# --- 3. Fonts ---
FONT_BOLD = ("sans-serif", 13, "bold")
FONT_NORMAL = ("sans-serif", 13)
FONT_LARGE_BOLD = ("sans-serif", 24, "bold")
MATRIX_FONT_BOLD = ("sans-serif", 12, "bold")
MATRIX_RESULT_FONT = ("sans-serif", 11)


# --- 4. Sizes & Geometry ---
# General
HIGHLIGHT_BORDER_WIDTH = 2
MAIN_WINDOW_GEOMETRY = "520x650"
NOTIFICATION_POPUP_ALPHA = 0.95
ACTION_SELECTOR_BUTTON_HEIGHT = 35
ACTION_SELECTOR_SPACING = 5
ACTION_SELECTOR_MARGIN = 10

# Window Sizes
ACTION_SELECTOR_GEOMETRY = "380x550"
PROMPT_EDITOR_GEOMETRY = "550x750"
SETTINGS_WINDOW_GEOMETRY = "540x500"
MATRIX_WINDOW_GEOMETRY = "1400x800"
MATRIX_POPUP_GEOMETRY = "450x450"
HISTORY_SELECTOR_POPUP_WIDTH = 380
HISTORY_SELECTOR_POPUP_MAX_HEIGHT = 450
NOTIFICATION_POPUP_INITIAL_WIDTH = 500

# Matrix Component Sizes
MATRIX_IMAGE_THUMBNAIL_SIZE = (50, 50)
MATRIX_RESULT_CELL_HEIGHT = 60
MATRIX_CELL_WIDTH = 250
MATRIX_FIXED_COL_WIDTH = 260
