name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: windows-latest  # primary tested platform
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt || echo "dev deps optional"
      - name: Syntax check (compileall)
        run: |
          python - << 'PY'
          import compileall
          import sys
          ok = compileall.compile_dir('.', maxlevels=10, quiet=1)
          sys.exit(0 if ok else 1)
          PY

